        # Root logger
        log4j.rootLogger=INFO, console, file
        log4j.debug=true

        # Console appender
        log4j.appender.console=org.apache.log4j.ConsoleAppender
        log4j.appender.console.layout=org.apache.log4j.PatternLayout
        log4j.appender.console.layout.ConversionPattern=%d{HH:mm:ss} %-5p %c{1} - %m%n

        # File appender
        log4j.appender.file=org.apache.log4j.RollingFileAppender
        log4j.appender.file.File=${user.dir}/logs/tickmaster.log
        log4j.appender.file.MaxFileSize=10MB
        log4j.appender.file.MaxBackupIndex=10
        log4j.appender.file.layout=org.apache.log4j.PatternLayout
        log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} - %m%n

        # Tu paquete en DEBUG
        log4j.logger.edu.upb.tickmaster=DEBUG