# path=HandlerClassName
/api/v1/clients=edu.upb.tickmaster.httpserver.handlers.ClientsGetHandler
/api/v1/clients/add=edu.upb.tickmaster.httpserver.handlers.ClientsPostHandler
/api/v1/eventos=edu.upb.tickmaster.httpserver.handlers.EventGetHandler
/api/v1/eventos/add=edu.upb.tickmaster.httpserver.handlers.EventPostHandler
/api/v1/tickets=edu.upb.tickmaster.httpserver.handlers.TicketGetHandler
/api/v1/facturas=edu.upb.tickmaster.httpserver.handlers.FacturaGetHandler
/api/v1/compra=edu.upb.tickmaster.httpserver.handlers.CompraHandler
/api/v1/sectores=edu.upb.tickmaster.httpserver.handlers.SectorGetHandler
/api/v1/login=edu.upb.tickmaster.httpserver.handlers.LoginHandler
/api/v1/register=edu.upb.tickmaster.httpserver.handlers.RegisterHandler